In [15]:
"""  বিভিন্ন model import করবো কিবাভে ?  """

# Pandas
import pandas as pd

# numpy
import numpy as np

# লজিস্টিক রিগ্রেশন
from sklearn.linear_model import LogisticRegression

# ডিসিশন ট্রি
from sklearn.tree import DecisionTreeClassifier

# লিনিয়ার রিগ্রেশন
from sklearn.linear_model import LinearRegression

# KMeans
from sklearn.cluster import KMeans

# matplotlib
import matplotlib.pyplot as plt

# iris
from sklearn.datasets import load_iris

# ৩ডি প্লটের জন্য
from mpl_toolkits.mplot3d import Axes3D

# স্ট্যাটিস্টিক্যাল ভিজুয়ালাইজেশনের জন্য
import seaborn as sns

# ডেটাকে ট্রেন ও টেস্ট সেটে ভাগ করার jonno
from sklearn.model_selection import train_test_split

# for file upload ar jonno
from google.colab import files


In [27]:
# file upload
files.upload()

Saving Salary_Data (1).csv to Salary_Data (1) (2).csv


{'Salary_Data (1) (2).csv': b'YearsExperience,Salary\r\n1.1,39343\r\n1.3,46205\r\n1.5,37731\r\n2,43525\r\n2.2,39891\r\n2.9,56642\r\n,60150\r\n3.2,54445\r\n3.2,64445\r\n3.7,57189\r\n3.9,63218\r\n,55794\r\n4,56957\r\n4.1,57081\r\n4.5,61111\r\n4.9,67938\r\n,66029\r\n5.3,83088\r\n5.9,81363\r\n6,93940\r\n6.8,91738\r\n7.1,98273\r\n7.9,101302\r\n8.2,113812\r\n,109431\r\n9,105582\r\n9.5,116969\r\n9.6,112635\r\n10.3,122391\r\n10.5,121872\r\n'}

In [28]:
# file Read
df = pd.read_csv('/content/Salary_Data (1).csv')

In [29]:
# data show
df.sample(10)

,YearsExperience,Salary
23,8.2,113812
11,NaN,55794
7,3.2,54445
6,NaN,60150
28,10.3,122391
22,7.9,101302
19,6.0,93940
1,1.3,46205
18,5.9,81363
29,10.5,121872


In [30]:
#

In [32]:
iris = load_iris()
x = iris.data
y = iris.target

In [33]:
""" Dataset set split  করবো কিবাভে ? """
"""
split করার আগে উপরের ৩ টা লাইন ডিক্লেয়ার করতে হবে না হলে error দেখাবে ! যেমন:  'x' is not defined
'y ' is not defined
"""
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size = 0.2, # ২০% ডেটা টেস্ট, ৮০% ট্রেন।
    random_state = 42, # ফলাফল রিপিট করতে

)

In [37]:
""" Model Training , Testing, করবো কিভাবে ? """

# মডেল ট্রেন
model = LogisticRegression()
model.fit(x_train, y_train)

# মডেল টেস্ট করা
accuracy = model.score(x_test, y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 1.0


In [38]:
#

In [43]:
""" Data Predication করবো কিভাবে ? """
y_pred = model.predict(x_test)
y_pred_proba = model.predict_proba(x_test)

# z = w1 * x + w0
# y_pred = sigmoid(z)
# print(y_pred)


In [52]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [65]:
"""  Confusion metric classification কি
এটা মডেলের প্রেডিকশন কতটা সঠিক/ভুল হয়েছে তা দেখানোর একটি টেবিল। """

# গুরুত্বপূর্ণ মেট্রিক্স বের করা যেমন : একুরেসি, প্রিসিশন, রিকল বের করা

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

# Precisin
precision = precision_score(y_test, y_pred)

# Recall
recall = recall_score(y_test, y_pred)


print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [ ]:
# Performance Metrics (পারফরম্যান্স মেট্রিক্স) কি?
# মেট্রিক্স গুলো বলে দেয় আপনার মডেল কতটা ভালো কাজ করছে।

In [70]:
from sklearn.metrics import classification_report
#F1 = 2 x (Precision x Recall) / (Precision + Recall)

print(classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.45      1.00      0.62         9
           2       0.00      0.00      0.00        11

    accuracy                           0.63        30
   macro avg       0.48      0.67      0.54        30
weighted avg       0.47      0.63      0.52        30



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [77]:
# কে মডেল ফিট করে এবং প্রেডিকশন করে?
# আপনার Logistic Regression কোডে, মডেল ফিট করা এবং প্রেডিকশন করা হচ্ছে
from sklearn.metrics import accuracy_score, confusion_matrix

In [73]:
# মডেল ফিট করা (Training)
model = LogisticRegression()
model.fit(x_train, y_train)

print("\n মডেল ট্রেনিং সম্পন্ন!")
print(f"মডেলের coef (w1): {model.coef_[0][0]:.4f}")
print(f"মডেলের intercept (w0): {model.intercept_[0]:.4f}")


 মডেল ট্রেনিং সম্পন্ন!
মডেলের coef (w1): -0.3935
মডেলের intercept (w0): 9.0088


In [74]:
#  প্রেডিকশন করা
y_pred = model.predict(x_test)
y_pred_proba = model.predict_proba(x_test)


print("\n" + "="*50)
print("প্রেডিকশন ফলাফল:")
print("="*50)


প্রেডিকশন ফলাফল:


In [75]:
# একুরেসি
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy: {accuracy*100:.2f}%")

Model Accuracy: {accuracy*100:.2f}%


In [78]:
# কনফিউশন ম্যাট্রিক্স
cm = confusion_matrix(y_test, y_pred)
print("\n Confusion Matrix :")
print(cm)


 Confusion Matrix :
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
